#!/bin/bash
# 机器人数据收集自动化 - 快速命令参考
# 保存为 check_robot_system.sh 方便使用

echo "========================================="
echo "🤖 机器人数据收集系统 - 快速命令参考"
echo "========================================="
echo ""

WORKSPACE="/home/admin/.openclaw/workspace"
SCRIPTS="$WORKSPACE/scripts"
LOGS="$WORKSPACE/logs"
REPORTS="$WORKSPACE/reports"

echo "📁 工作目录：$WORKSPACE"
echo ""

echo "【1. 查看系统状态】"
echo "-------------------------------------------"
echo "# 查看定时任务"
echo "crontab -l"
echo ""
echo "# 查看 Cron 服务状态"
echo "systemctl status cron"
echo ""
echo "# 查看今日 Token 使用"
echo "cat $LOGS/token_stats.json | python3 -m json.tool"
echo ""

echo "【2. 查看日志】"
echo "-------------------------------------------"
echo "# 查看最新日志"
echo "tail -50 $LOGS/机器人数据收集_*.log"
echo ""
echo "# 实时查看日志"
echo "tail -f $LOGS/机器人数据收集_*.log"
echo ""
echo "# 查看定时任务日志"
echo "tail -50 $LOGS/cron_robot_collection.log"
echo ""

echo "【3. 手动执行】"
echo "-------------------------------------------"
echo "# 执行数据收集"
echo "bash $SCRIPTS/run_robot_collection.sh"
echo ""
echo "# 生成日报"
echo "bash $SCRIPTS/push_daily_report.sh"
echo ""
echo "# 直接运行 Python 脚本"
echo "cd $WORKSPACE && PYTHONPATH=\$HOME/.local/lib/python3.6/site-packages:\$PYTHONPATH python3 $SCRIPTS/机器人数据收集自动化.py"
echo ""

echo "【4. 查看报告】"
echo "-------------------------------------------"
echo "# 查看今日日报"
echo "cat $REPORTS/\$(date +%Y-%m-%d)_机器人数据收集日报.md"
echo ""
echo "# 查看历史报告"
echo "ls -lh $REPORTS/"
echo ""

echo "【5. 数据库管理】"
echo "-------------------------------------------"
echo "# 查看数据库记录数"
echo "wc -l $WORKSPACE/机器人数据库_核心版.csv"
echo ""
echo "# 备份数据库"
echo "cp $WORKSPACE/机器人数据库_核心版.csv $WORKSPACE/backup/机器人数据库_\$(date +%Y%m%d).csv"
echo ""
echo "# 查看备份"
echo "ls -lh $WORKSPACE/backup/"
echo ""

echo "【6. 定时任务管理】"
echo "-------------------------------------------"
echo "# 查看已安装的任务"
echo "crontab -l"
echo ""
echo "# 编辑任务"
echo "crontab -e"
echo ""
echo "# 重新安装配置"
echo "crontab $SCRIPTS/robot_collection_cron.conf"
echo ""
echo "# 删除所有任务"
echo "crontab -r"
echo ""

echo "【7. 故障排查】"
echo "-------------------------------------------"
echo "# 检查 Python 版本"
echo "python3 --version"
echo ""
echo "# 检查依赖"
echo "pip3 list | grep -E 'requests|beautifulsoup4'"
echo ""
echo "# 检查脚本权限"
echo "ls -l $SCRIPTS/*.sh"
echo ""
echo "# 修复脚本权限"
echo "chmod +x $SCRIPTS/*.sh"
echo ""
echo "# 检查目录权限"
echo "ls -ld $LOGS $REPORTS $WORKSPACE/backup"
echo ""

echo "【8. 系统清理】"
echo "-------------------------------------------"
echo "# 清理 30 天前的日志"
echo "find $LOGS -name '机器人数据收集_*.log' -mtime +30 -delete"
echo ""
echo "# 清理 30 天前的报告"
echo "find $REPORTS -name '*.md' -mtime +30 -delete"
echo ""

echo "【9. 快速测试】"
echo "-------------------------------------------"
echo "# 测试 Python 脚本语法"
echo "python3 -m py_compile $SCRIPTS/机器人数据收集自动化.py"
echo ""
echo "# 测试脚本执行（60 秒超时）"
echo "cd $WORKSPACE && timeout 60 python3 $SCRIPTS/机器人数据收集自动化.py"
echo ""

echo "========================================="
echo "📚 文档位置:"
echo "   - 使用文档：$SCRIPTS/README_机器人数据收集自动化.md"
echo "   - 安装指南：$SCRIPTS/INSTALL_机器人数据收集自动化.md"
echo "   - 部署报告：$WORKSPACE/机器人数据收集自动化_部署完成报告.md"
echo "========================================="
echo ""
echo "💡 提示：将此脚本保存为 check_robot_system.sh，运行 ./check_robot_system.sh 查看"
